apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # app.kubernetes.io/app: {PLACEHOLDER}
  # app.kubernetes.io/component: {PLACEHOLDER}
  # app.kubernetes.io/part-of: {PLACEHOLDER}
  app.kubernetes.io/origin: dyamand
resources:
#replace me
#- deployment.yaml
#- service.yaml
#- ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
#configMapGenerator:
#- name: {PLACEHOLDER}
# envs:
# - config.env
